token.expire=60000
DATABASE_URL=jdbc:mysql://mysql-11a26fc-aifood.h.aivencloud.com:20769/defaultdb?useSSL=true&requireSSL=true
DATABASE_USERNAME=avnadmin
DATABASE_PASSWORD=AVNS_zld_DCXK3qBIMyTqV57
REDIS_HOST=chief-spider-96397.upstash.io
REDIS_PORT= 6379
REDIS_PASSWORD=gQAAAAAAAXiNAAIgcDJlMzU4Yjg5YTIwOWQ0MzUwOTVlNzk2MDEzYjBhODgxZA

